url: https://job-track.github.io
baseurl: /

# Site settings
title: JOBTRACK
email: khusikadhamar@gmail.com
description: "JOBTRACK is an apps to find the job"


# Team names, titles and social links
people:
- name: Muhammad Azzumardi Azra
  pic: 1
  position: CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Khusika Dhamar Gusti
  pic: 2
  position: Android & Web Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: http://github.com/job-track

# Postal address (add as many lines as necessary)
address:
  - line: Malang
  - line: Jawa Timur, Indonesia

# Build settings
markdown: kramdown
permalink: pretty
